= rust macro bug
v0.1, 2023-01-03
Michael Stone
:homepage: https://github.com/mstone/rust-macro-bug
:sectlinks:
:icons: font

== Introduction

This repo is a minimal reproducer for a proc-macro bug that I struggled to track down.

The proc-macro that exhibits the bug is

[source,rust]
----
#![feature(proc_macro_span)]
use quote::{ToTokens};
use syn::{parse_macro_input, Item, Expr, visit_mut::VisitMut};

struct Parts {}

impl<'ast> VisitMut for Parts {
    fn visit_expr_mut(&mut self, expr: &mut Expr) {
        syn::visit_mut::visit_expr_mut(self, expr);

        let expr_clone = expr.clone();
        *expr = syn::Expr::Block(syn::ExprBlock{
            attrs: vec![],
            label: None,
            block: syn::Block{
                brace_token: syn::token::Brace::default(),
                stmts: vec![syn::Stmt::Expr(expr_clone)],
            },
        });
    }
}

#[proc_macro_attribute]
pub fn bug(args: proc_macro::TokenStream, input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let _ = args;
    let mut input = parse_macro_input!(input as Item);

    let mut parts = Parts{};
    parts.visit_item_mut(&mut input);
    
    let tokens = input.into_token_stream();
    tokens.into()
}
----

== Steps to reproduce

[source,bash]
----
nix develop
cargo test # fails to compile
----

The bug is visible at expansion-time by running:

[source,bash]
----
cargo expand --ugly --test 01-bug
----

which produces a surprise `(/\*ERROR*/)` where there should be a `{ b }` sub-expression, see callout (1) below:

[source,rust]
----
...
fn add(a: u64, b: u64) -> u64 { { { a } (/*ERROR*/) } } // <1>
...
----

<1> What is printing `(/\*ERROR*/)` here? -- This should be `{ b }` -- why isn't it?


== Expected Behavior

[source,bash]
----
cargo test
----

should succeed, and 

[source,bash]
----
cargo expand --ugly --test 01-bug 2>/dev/null | grep 'fn add'
----

should produce as output:

----
fn add(a: u64, b: u64) -> u64 { { { a } { b } } }
----

== Conclusion

It turns out that there's a couple of things going on here, all driven by a bug in the initial proc-macro itself, which is that expressions need to be parenthesized as well as braced; otherwise, the result is invalid rust syntax, as is demonstrated by link:https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=fn%20add(a%3A%20u64%2C%20b%3A%20u64)%20-%3E%20u64%20%7B%20%7B%20%7B%20a%20%7D%20%2B%20%7B%20b%20%7D%20%7D%20%7D[this playground].

From there, it turns out that the further surprising `(/\*ERROR*/)` sub-term in the expanded output is the result of rustc's `-Z unpretty=expanded` attempt to indicate the above error, as implemented in link:https://github.com/rust-lang/rust/blob/ddad1e1f15f77074738bb3d7fb7688a9177b6450/compiler/rustc_ast_pretty/src/pprust/state/expr.rs#L557[rustc_ast_pretty/.../expr.rs].